version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
     - "mongo_config:/data/configdb"
     - "mongo_data:/data/db"
     - "./backups:/data/backups"
  node:
    build: .
    restart: always
    environment:
     - API_SECRET=superunsecuresecret
     - MONGO_URI=mongodb://mongo/3dpixels
    links:
     - mongo
    ports:
     - "127.0.0.1:8081:8081"
volumes:
  mongo_config:
  mongo_data:
